name: Run Jest Tests

on:
  pull_request:
    branches:
      - main
  deployment_status:

jobs:
  # test-jest:
  #   runs-on: self-hosted
  #   if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         token: ${{ secrets.GH_PAT }}

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "lts/*"

  #     - name: Install dependencies using pnpm
  #       run: |
  #         npm install -g pnpm
  #         pnpm install

  #     - name: Run tests
  #       run: pnpm test
  #       # run: pnpm test:coverage

  # - name: Commit coverage results
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  #   run: |
  #     git config --global user.name 'Luis Ignacio'
  #     git config --global user.email 'luisignacioccp@gmail.com'
  #     BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
  #     git add public/coverage/
  #     git commit -m "Add updated coverage results [skip ci]"
  #     git push origin $BRANCH_NAME
  #   if: success()

  test-cypress:
    runs-on: self-hosted
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies using pnpm
        run: |
          npm install -g pnpm
          pnpm install

      - name: Install required libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libgtk2.0-0 \
            libgtk-3-0 \
            libgbm-dev \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libasound2 \
            libxtst6 \
            xauth \
            libatk1.0-0  # Agrega esta l√≠nea para instalar libatk-1.0

      - name: Run Cypress tests
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
        run: |
          npx xvfb-maybe npx cypress run --config baseUrl=$BASE_URL
